`timescale 1ns / 1ps

// ─────────────────────────────────────────────────────────────────────────────
// I2C Master — single register read (write-pointer then read-data transaction)
//
// WHAT THIS MODULE DOES:
//   When 'start' pulses high for one cycle it executes this sequence on the bus:
//     START -> [dev_addr | W] -> ACK -> [reg_addr] -> ACK ->
//     RSTART -> [dev_addr | R] -> ACK -> [8 data bits] -> NACK -> STOP
//   rx_data holds the byte returned; rx_valid pulses high for one cycle when done.
//
// EE ANALOGY:
//   Think of this as a UART shift register + prescaler, except the clock (SCL)
//   is generated by this module itself and there are special bus conditions
//   (START/STOP) that live above the bit level.
//
// OPEN-DRAIN NOTE:
//   I2C uses open-drain lines — you never drive the bus HIGH.
//   You either pull it LOW or release it (Hi-Z, pulled up externally by resistors).
//   The SDA tristate at the bottom of this file implements that.
// ─────────────────────────────────────────────────────────────────────────────

module i2c_master (
  input  logic       clk,
  input  logic       rst_n,
  input  logic       start,      // pulse high for 1 cycle to begin a read
  input  logic [6:0] dev_addr,   // 7-bit I2C device address
  input  logic [7:0] reg_addr,   // register to read from the device
  output logic [7:0] rx_data,    // byte received from the device
  output logic       rx_valid,   // pulses high for 1 cycle when rx_data is ready
  output logic       i2c_scl,
  inout  wire        i2c_sda
);

  // ── 1. PHASE COUNTER (the prescaler / timing source) ─────────────────────
  //
  // 50 MHz system clock, 100 kHz I2C target -> 500 system clocks per I2C bit.
  // We divide each bit-period into 4 equal phases (125 cycles each):
  //
  //   phase 0 -- SCL low,  SDA may change   (setup time)
  //   phase 1 -- SCL rises, SDA must be stable
  //   phase 2 -- SCL high, SDA is sampled by target (or we sample it)
  //   phase 3 -- SCL falls, shift / advance to next bit
  //
  // All FSM decisions happen on the 'tick' pulse (the moment phase advances).
  // Because tick fires with the OLD phase value visible, a case on phase 0
  // executes its action and then phase becomes 1 on the very next cycle.

  localparam CLK_DIV = 125;  // cycles per phase (125 x 4 phases = 500 = 50MHz/100kHz)

  logic [6:0] clk_cnt;  // counts 0..CLK_DIV-1
  logic [1:0] phase;    // 0..3, wraps automatically (2-bit)
  logic       tick;     // 1-cycle pulse at the end of each phase

  assign tick = (clk_cnt == CLK_DIV - 1);

  // ── FSM state declaration (here so phase counter can reference IDLE) ──────
  typedef enum logic [3:0] {
    IDLE,
    START,    // issue START condition  (SDA falls while SCL is high)
    ADDR_W,   // send {dev_addr, 1'b0}  (7-bit address + WRITE bit)
    ACK_AW,   // wait one bit for target ACK
    REG,      // send reg_addr byte
    ACK_REG,  // wait one bit for target ACK
    RSTART,   // issue REPEATED START   (SDA falls while SCL is high, mid-transaction)
    ADDR_R,   // send {dev_addr, 1'b1}  (7-bit address + READ bit)
    ACK_AR,   // wait one bit for target ACK
    READ,     // clock in 8 data bits from target
    NACK,     // master holds SDA high (NACK) to tell target we are done reading
    STOP      // issue STOP condition   (SDA rises while SCL is high)
  } state_t;

  state_t state;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      clk_cnt <= '0;
      phase   <= '0;
    end else if (state == IDLE) begin  // hold at zero while idle -- clean re-entry
      clk_cnt <= '0;
      phase   <= '0;
    end else if (tick) begin
      clk_cnt <= '0;
      phase   <= phase + 1'b1;        // 2-bit: rolls 3->0 on its own
    end else begin
      clk_cnt <= clk_cnt + 1'b1;
    end
  end


  // ── 2. SDA TRISTATE DRIVER ────────────────────────────────────────────────
  //
  // Two internal signals control the open-drain output:
  //   sda_oe  -- output enable: 1 = we are driving, 0 = release
  //   sda_out -- the value we want (only 0 is meaningful; Hi-Z replaces 1)
  //
  // Result on the pin:
  //   oe=1, out=0  -> pin driven LOW   (we are pulling the bus down)
  //   oe=0         -> pin = Hi-Z       (external pull-up resistor holds it HIGH)
  //   oe=1, out=1  -> pin = Hi-Z       (same -- never actively drive high)

  logic sda_out, sda_oe;

  assign i2c_sda = (sda_oe & ~sda_out) ? 1'b0 : 1'bz;


  // ── 3. FSM STATE DEFINITIONS ─────────────────────────────────────────────
  //
  // Each state handles ONE step of the I2C transaction.
  // States that send a full byte (ADDR_W, REG, ADDR_R) stay in that state for
  // 8 bit-periods, using bit_cnt to track progress.
  // (typedef and state declaration moved above the phase counter always_ff block)


  // ── 4. BIT COUNTER AND SHIFT REGISTER ────────────────────────────────────
  //
  // shift_reg: loaded with the byte to send, shifted LEFT each bit so MSB
  //            exits first -- bit[7] is always the "next to transmit" bit.
  // bit_cnt:   counts from 7 down to 0; when it hits 0 we have sent all 8 bits.
  // rx_buf:    shifted LEFT as bits arrive; bit[0] of i2c_sda is appended LSB.

  logic [2:0] bit_cnt;
  logic [7:0] shift_reg;
  logic [7:0] rx_buf;


  // ── 5. MAIN FSM (sequential) ─────────────────────────────────────────────
  //
  // Everything lives in one always_ff block so there is only one driver for
  // each signal -- avoids the "multiple driver" issue.
  //
  // PATTERN inside each state:
  //   if (tick) begin        <- wait for the phase boundary
  //     case (phase)         <- which of the 4 sub-phases just ended
  //       ...
  //     endcase
  //   end
  //
  // Transitions to the next state always happen at phase 3 (the falling-edge
  // phase), so every new state always begins cleanly at phase 0.

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state     <= IDLE;
      i2c_scl   <= 1'b1;   // I2C idle = both lines high
      sda_out   <= 1'b1;
      sda_oe    <= 1'b0;   // release bus on reset
      rx_valid  <= 1'b0;
      rx_data   <= '0;
      bit_cnt   <= 3'd7;
      shift_reg <= '0;
      rx_buf    <= '0;
    end else begin

      rx_valid <= 1'b0;  // default: deassert every cycle; only pulse in NACK

      case (state)

        // ── IDLE ─────────────────────────────────────────────────────────────
        // Bus is idle: both SCL and SDA high.
        // Wait for a 'start' pulse from the outside.
        IDLE: begin
          i2c_scl <= 1'b1;
          sda_out <= 1'b1;
          sda_oe  <= 1'b0;   // release -- don't own the bus yet
          if (start) begin
            sda_oe <= 1'b1;  // take ownership of SDA before pulling it low
            state  <= START;
          end
        end

        // ── START condition ───────────────────────────────────────────────────
        // SCL is still HIGH from IDLE.
        // phase 0: pull SDA low -> this is the START condition seen by the target
        // phase 1: pull SCL low -> hold bus, ready to clock data
        // phase 2: load the first byte into shift_reg while waiting
        // phase 3: transition; ADDR_W will begin at phase 0
        START: begin
          if (tick) begin
            case (phase)
              2'd0: sda_out <= 1'b0;               // SDA falls (SCL still high) = START
              2'd1: i2c_scl <= 1'b0;               // SCL falls, bus is held
              2'd2: begin
                shift_reg <= {dev_addr, 1'b0};     // address + WRITE bit
                bit_cnt   <= 3'd7;
              end
              2'd3: state <= ADDR_W;
            endcase
          end
        end

        // ── Send address + WRITE bit ──────────────────────────────────────────
        // Shifts out 8 bits, MSB first.
        // phase 0: SCL low, put the next bit on SDA
        // phase 1: SCL rises -- target latches SDA here
        // phase 2: SCL high, hold
        // phase 3: SCL falls, advance (shift left, decrement counter)
        ADDR_W: begin
          if (tick) begin
            case (phase)
              2'd0: begin
                i2c_scl <= 1'b0;
                sda_out <= shift_reg[7];           // MSB first
              end
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;                              // hold, target is sampling
              2'd3: begin
                i2c_scl   <= 1'b0;
                shift_reg <= {shift_reg[6:0], 1'b0};  // shift left, fill with 0
                if (bit_cnt == 3'd0) begin
                  sda_oe <= 1'b0;                // release SDA so target can ACK
                  state  <= ACK_AW;
                end else
                  bit_cnt <= bit_cnt - 1'b1;
              end
            endcase
          end
        end

        // ── ACK after address+write ───────────────────────────────────────────
        // Target pulls SDA low during this bit-period to acknowledge.
        // We release SDA (sda_oe=0) and let the target drive.
        ACK_AW: begin
          if (tick) begin
            case (phase)
              2'd0: i2c_scl <= 1'b0;
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;                              // target holds SDA low (ACK)
              2'd3: begin
                i2c_scl   <= 1'b0;
                shift_reg <= reg_addr;             // load register address
                bit_cnt   <= 3'd7;
                sda_oe    <= 1'b1;                 // take back SDA
                state     <= REG;
              end
            endcase
          end
        end

        // ── Send register address byte ────────────────────────────────────────
        // Identical pattern to ADDR_W.
        REG: begin
          if (tick) begin
            case (phase)
              2'd0: begin
                i2c_scl <= 1'b0;
                sda_out <= shift_reg[7];
              end
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;
              2'd3: begin
                i2c_scl   <= 1'b0;
                shift_reg <= {shift_reg[6:0], 1'b0};
                if (bit_cnt == 3'd0) begin
                  sda_oe <= 1'b0;
                  state  <= ACK_REG;
                end else
                  bit_cnt <= bit_cnt - 1'b1;
              end
            endcase
          end
        end

        // ── ACK after register address ────────────────────────────────────────
        ACK_REG: begin
          if (tick) begin
            case (phase)
              2'd0: i2c_scl <= 1'b0;
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;
              2'd3: begin
                i2c_scl <= 1'b0;
                sda_out <= 1'b1;   // SDA must be HIGH before RSTART SCL rise
                sda_oe  <= 1'b1;   // we own SDA again for the repeated-START
                state   <= RSTART;
              end
            endcase
          end
        end

        // ── REPEATED START condition ──────────────────────────────────────────
        // Same electrical event as START but happens mid-transaction
        // (no STOP issued first). Required to switch from WRITE to READ phase.
        //
        // phase 0: SCL low, SDA high (set in ACK_REG exit)
        // phase 1: SCL rises -- SDA is high, bus looks idle momentarily
        // phase 2: SDA falls while SCL is HIGH -> REPEATED START seen by target
        // phase 3: SCL falls, load address+READ, go to ADDR_R
        RSTART: begin
          if (tick) begin
            case (phase)
              2'd0: begin
                i2c_scl <= 1'b0;
                sda_out <= 1'b1;               // ensure SDA is high as SCL rises
              end
              2'd1: i2c_scl <= 1'b1;           // SCL rises (SDA still high -- OK)
              2'd2: sda_out <= 1'b0;           // SDA FALLS while SCL high = RSTART
              2'd3: begin
                i2c_scl   <= 1'b0;
                shift_reg <= {dev_addr, 1'b1}; // address + READ bit
                bit_cnt   <= 3'd7;
                state     <= ADDR_R;
              end
            endcase
          end
        end

        // ── Send address + READ bit ───────────────────────────────────────────
        ADDR_R: begin
          if (tick) begin
            case (phase)
              2'd0: begin
                i2c_scl <= 1'b0;
                sda_out <= shift_reg[7];
              end
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;
              2'd3: begin
                i2c_scl   <= 1'b0;
                shift_reg <= {shift_reg[6:0], 1'b0};
                if (bit_cnt == 3'd0) begin
                  sda_oe <= 1'b0;            // release SDA: target will drive data
                  state  <= ACK_AR;
                end else
                  bit_cnt <= bit_cnt - 1'b1;
              end
            endcase
          end
        end

        // ── ACK after address+read ────────────────────────────────────────────
        ACK_AR: begin
          if (tick) begin
            case (phase)
              2'd0: i2c_scl <= 1'b0;
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;
              2'd3: begin
                i2c_scl <= 1'b0;
                bit_cnt <= 3'd7;
                rx_buf  <= '0;
                // sda_oe stays 0 -- target continues to drive SDA with data bits
                state   <= READ;
              end
            endcase
          end
        end

        // ── READ 8 data bits ──────────────────────────────────────────────────
        // We clock SCL and sample i2c_sda at phase 2 (SCL high, stable).
        // rx_buf is shifted LEFT and the new bit appended at bit[0],
        // so the first sample (MSB from target) lands in rx_buf[7].
        READ: begin
          if (tick) begin
            case (phase)
              2'd0: i2c_scl <= 1'b0;
              2'd1: i2c_scl <= 1'b1;
              2'd2: rx_buf  <= {rx_buf[6:0], i2c_sda};  // sample here
              2'd3: begin
                i2c_scl <= 1'b0;
                if (bit_cnt == 3'd0) begin
                  sda_oe  <= 1'b1;   // take back SDA to send NACK
                  sda_out <= 1'b1;   // NACK = hold SDA HIGH during ACK slot
                  state   <= NACK;
                end else
                  bit_cnt <= bit_cnt - 1'b1;
              end
            endcase
          end
        end

        // ── NACK ──────────────────────────────────────────────────────────────
        // Master holds SDA HIGH for one bit-period.
        // This tells the target "I have enough data, stop sending."
        NACK: begin
          if (tick) begin
            case (phase)
              2'd0: i2c_scl <= 1'b0;
              2'd1: i2c_scl <= 1'b1;
              2'd2: ;                          // SDA high (NACK), target reads it
              2'd3: begin
                i2c_scl  <= 1'b0;
                rx_data  <= rx_buf;            // latch the received byte
                rx_valid <= 1'b1;              // tell upstream data is ready
                sda_out  <= 1'b0;             // SDA low before STOP SCL rise
                state    <= STOP;
              end
            endcase
          end
        end

        // ── STOP condition ────────────────────────────────────────────────────
        // SCL rises while SDA is LOW, then SDA rises while SCL is still HIGH.
        // Mirror image of START.
        STOP: begin
          if (tick) begin
            case (phase)
              2'd0: begin
                i2c_scl <= 1'b0;
                sda_out <= 1'b0;               // ensure SDA is low before SCL rises
              end
              2'd1: i2c_scl <= 1'b1;           // SCL rises
              2'd2: sda_out <= 1'b1;           // SDA rises while SCL high = STOP
              2'd3: begin
                sda_oe <= 1'b0;               // release bus, done
                state  <= IDLE;
              end
            endcase
          end
        end

        default: state <= IDLE;

      endcase
    end
  end

endmodule
